general {
    lock_cmd = omarchy-lock-screen                         # lock screen and 1password
    before_sleep_cmd = loginctl lock-session               # lock before suspend.
    after_sleep_cmd = sleep 1 && hyprctl dispatch dpms on  # delay for PAM readiness, then turn on display.
    inhibit_sleep = 3                                      # wait until screen is locked
}
# 1. スクリーンセーバー（例：10分 = 600秒）
listener {
    timeout = 600                                             
    on-timeout = pidof hyprlock || omarchy-launch-screensaver 
}

# 2. 画面ロック（例：11分 = 660秒）
# セーバーが動いてから少し後にロックするのがスムーズです
listener {
    timeout = 900                                     
    on-timeout = loginctl lock-session 
}

# 3. 画面オフ ＆ キーボード消灯（例：15分 = 900秒）
listener {
    timeout = 1800                                            
    on-timeout = brightnessctl -sd '*::kbd_backlight' set 0  
    on-resume = brightnessctl -rd '*::kbd_backlight'         
}

listener {
    timeout = 1800                                            
    on-timeout = hyprctl dispatch dpms off                   
    on-resume = hyprctl dispatch dpms on && brightnessctl -r 
}
