-- Generated by nwg-displays on 2026-09-05 at 09:06:05. Do not edit manually.

hl.monitor({
    output = "HDMI-A-1",
    mode = "2560x1600@60.0",
    position = "1920x1440",
    scale = 1.2
})
hl.monitor({
    output = "DP-1",
    mode = "2560x1440@170.0",
    position = "1920x0",
    scale = 1
})
hl.monitor({
    output = "DP-2",
    mode = "1920x1080@143.86",
    position = "840x0",
    scale = 1.0,
    transform = 1
})
